name: inventory_management_system
description: "Local Inventory & POS System (LIPS) for the Iraqi market."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  
  # Database
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  sqlite3_flutter_libs: any
  path_provider: ^2.1.5
  path: ^1.9.0
  
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Routing
  go_router: ^14.0.0
  
  # Fonts
  google_fonts: any
  
  # Charts
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.1
  build_runner: ^2.10.5
  inno_bundle: ^0.11.2

flutter:
  generate: true
  uses-material-design: true

inno_bundle:
  id: 039d713c-398c-45d4-9e30-31344b702d6e
  publisher: Hassan Basim
